-- This statement inserts all the provided keywords from the three categories
-- (medical supplies, supplements, and vitamins) into the dtc_keywords table.
-- The ON CONFLICT clause prevents errors if you run the script multiple times,
-- it will simply do nothing if a keyword with the same combination of
-- search_term, category, and keyword_en already exists.

INSERT INTO public.dtc_keywords (category, search_term, keyword_en) VALUES
-- Medical Supplies
('medical supplies', 'อุปกรณ์การแพทย์', 'medical equipment'),
('medical supplies', 'เวชภัณฑ์', 'medical supplies'),
('medical supplies', 'อุปกรณ์ปฐมพยาบาล', 'first aid supplies'),
('medical supplies', 'หน้ากากอนามัย', 'face mask'),
('medical supplies', 'ถุงมือแพทย์', 'medical gloves'),
('medical supplies', 'แอลกอฮอล์ทางการแพทย์', 'medical alcohol'),
('medical supplies', 'น้ำยาฆ่าเชื้อ', 'disinfectant'),
('medical supplies', 'เตียงผู้ป่วย', 'hospital bed'),
('medical supplies', 'รถเข็นผู้ป่วย', 'wheelchair'),
('medical supplies', 'เครื่องวัดความดัน', 'blood pressure monitor'),
('medical supplies', 'เครื่องวัดออกซิเจนปลายนิ้ว', 'pulse oximeter'),
('medical supplies', 'เทอร์โมมิเตอร์วัดไข้', 'thermometer'),
('medical supplies', 'ชุดทำแผล', 'wound dressing kit'),
('medical supplies', 'ผ้าพันแผล', 'bandage'),
('medical supplies', 'พลาสเตอร์ยา', 'adhesive bandage'),
('medical supplies', 'สำลี', 'cotton wool'),
('medical supplies', 'ผ้าก๊อซ', 'gauze'),
('medical supplies', 'เข็มฉีดยา', 'syringe'),
('medical supplies', 'สายให้อาหาร', 'feeding tube'),
('medical supplies', 'ถุงเก็บปัสสาวะ', 'urine bag'),
('medical supplies', 'อุปกรณ์ช่วยหายใจ', 'respiratory equipment'),
('medical supplies', 'เครื่องผลิตออกซิเจน', 'oxygen concentrator'),
('medical supplies', 'กายภาพบำบัด', 'physical therapy equipment'),
('medical supplies', 'อุปกรณ์ผู้สูงอายุ', 'elderly care equipment'),
('medical supplies', 'อุปกรณ์ดูแลผู้ป่วยติดเตียง', 'bedridden patient care equipment'),
('medical supplies', 'ร้านขายอุปกรณ์การแพทย์', 'medical supply store'),
('medical supplies', 'เครื่องมือแพทย์', 'medical instruments'),
('medical supplies', 'suppliesทางการแพทย์', 'medical supplies (informal)'),
('medical supplies', 'medical supplies thailand', 'medical supplies thailand'),
('medical supplies', 'thai medical supplies', 'thai medical supplies'),
('medical supplies', 'home medical supplies thailand', 'home medical supplies thailand'),
('medical supplies', 'hospital supplies thailand', 'hospital supplies thailand'),
('medical supplies', 'medical equipment thailand', 'medical equipment thailand'),
('medical supplies', 'first aid kit thailand', 'first aid kit thailand'),
('medical supplies', 'ppe thailand', 'ppe thailand'),
('medical supplies', 'buy medical supplies thailand', 'buy medical supplies thailand'),
('medical supplies', 'online medical supply store thailand', 'online medical supply store thailand'),

-- Supplements
('supplements', 'อาหารเสริม', 'food supplement'),
('supplements', 'อาหารเสริมลดน้ำหนัก', 'weight loss supplement'),
('supplements', 'อาหารเสริมบำรุงผิว', 'skin care supplement'),
('supplements', 'อาหารเสริมเพิ่มน้ำหนัก', 'weight gain supplement'),
('supplements', 'อาหารเสริมกล้ามเนื้อ', 'muscle supplement'),
('supplements', 'อาหารเสริมผู้ชาย', 'men''s supplement'),
('supplements', 'อาหารเสริมผู้หญิง', 'women''s supplement'),
('supplements', 'อาหารเสริมเด็ก', 'children''s supplement'),
('supplements', 'อาหารเสริมนำเข้า', 'imported supplement'),
('supplements', 'อาหารเสริมพร้อมส่ง', 'ready-to-ship supplement'),
('supplements', 'อาหารเสริมราคาส่ง', 'wholesale supplement'),
('supplements', 'อาหารเสริม รีวิว', 'supplement review'),
('supplements', 'อาหารเสริมแนะนำ', 'recommended supplement'),
('supplements', 'อาหารเสริมถูก', 'cheap supplement'),
('supplements', 'อาหารเสริมจัดโปร', 'supplement promotion'),
('supplements', 'อาหารเสริมโปรโมชั่น', 'supplement promotion'),
('supplements', 'อาหารเสริมแท้ 100%', '100% genuine supplement'),
('supplements', 'ร้านอาหารเสริม', 'supplement shop'),
('supplements', 'ซื้ออาหารเสริมที่ไหนดี', 'where to buy supplements'),
('supplements', 'คอลลาเจน', 'collagen'),
('supplements', 'กลูต้าไธโอน', 'glutathione'),
('supplements', 'โปรตีน', 'protein'),
('supplements', 'เวย์โปรตีน', 'whey protein'),
('supplements', 'วิตามินรวม', 'multivitamin'),
('supplements', 'แคลเซียม', 'calcium'),
('supplements', 'ซิงค์', 'zinc'),
('supplements', 'แมกนีเซียม', 'magnesium'),
('supplements', 'โอเมก้า 3', 'omega 3'),
('supplements', 'โคคิวเท็น', 'coq10'),
('supplements', 'สารสกัดจากสมุนไพร', 'herbal extract'),
('supplements', 'อาหารเสริมออร์แกนิก', 'organic supplement'),
('supplements', 'supplements thailand', 'supplements thailand'),
('supplements', 'thai supplements', 'thai supplements'),
('supplements', 'buy supplements thailand', 'buy supplements thailand'),
('supplements', 'online supplement store thailand', 'online supplement store thailand'),
('supplements', 'best supplements thailand', 'best supplements thailand'),
('supplements', 'sports supplements thailand', 'sports supplements thailand'),
('supplements', 'health supplements thailand', 'health supplements thailand'),
('supplements', 'korean supplements thailand', 'korean supplements thailand'),
('supplements', 'japanese supplements thailand', 'japanese supplements thailand'),
('supplements', 'us supplements thailand', 'us supplements thailand'),

-- Vitamins
('vitamins', 'วิตามิน', 'vitamin'),
('vitamins', 'อาหารเสริม', 'supplement'),
('vitamins', 'วิตามินของแท้', 'genuine vitamin'),
('vitamins', 'ร้านขายวิตามิน', 'vitamin shop'),
('vitamins', 'ร้านอาหารเสริม', 'supplement shop'),
('vitamins', 'วิตามินสุขภาพ', 'health vitamin'),
('vitamins', 'วิตามินผิว', 'skin vitamin'),
('vitamins', 'วิตามินผู้หญิง', 'women''s vitamin'),
('vitamins', 'วิตามินผู้ชาย', 'men''s vitamin'),
('vitamins', 'วิตามินเด็ก', 'children''s vitamin'),
('vitamins', 'วิตามินนำเข้า', 'imported vitamin'),
('vitamins', 'วิตามินญี่ปุ่น', 'Japanese vitamin'),
('vitamins', 'วิตามินเกาหลี', 'Korean vitamin'),
('vitamins', 'วิตามินอเมริกา', 'American vitamin'),
('vitamins', 'วิตามินบำรุงผิว', 'skin care vitamin'),
('vitamins', 'วิตามินบำรุงสมอง', 'brain vitamin'),
('vitamins', 'วิตามินบำรุงเลือด', 'blood vitamin'),
('vitamins', 'วิตามินบำรุงสายตา', 'eye vitamin'),
('vitamins', 'วิตามินบำรุงตับ', 'throat vitamin'),
('vitamins', 'วิตามินภูมิแพ้', 'allergic vitamin'),
('vitamins', 'วิตามินลดสิว', 'acne vitamin'),
('vitamins', 'วิตามินเพิ่มภูมิ', 'skin care vitamin'),
('vitamins', 'วิตามินเพิ่มน้ำหนัก', 'weight gain vitamin'),
('vitamins', 'วิตามินลดน้ำหนัก', 'weight loss vitamin'),
('vitamins', 'วิตามิน ราคาส่ง', 'wholesale vitamin'),
('vitamins', 'วิตามิน พร้อมส่ง', 'ready-to-ship vitamin'),
('vitamins', 'วิตามิน รีวิว', 'review vitamin'),
('vitamins', 'วิตามินแนะนำ', 'recommendation vitamin'),
('vitamins', 'วิตามินถูก', 'cheap vitamin'),
('vitamins', 'วิตามินจัดโปร', 'promotion vitamin'),
('vitamins', 'วิตามินโปรโมชั่น', 'promotion vitamin'),
('vitamins', 'วิตามินแท้ 100%', '100% genuine vitamin'),
('vitamins', 'vitamin shop thailand', 'vitamin shop thailand'),
('vitamins', 'organic vitamins thailand', 'organic vitamins thailand'),
('vitamins', 'vitamin skincare thailand', 'vitamin skincare thailand'),
('vitamins', 'thai supplement shop', 'thai supplement shop'),
('vitamins', 'glutathione thailand', 'glutathione thailand'),
('vitamins', 'collagen supplement thailand', 'collagen supplement thailand'),
('vitamins', 'imported vitamins thailand', 'imported vitamins thailand'),
('vitamins', 'multivitamin thailand', 'multivitamin thailand'),
('vitamins', 'best vitamins thailand', 'best vitamins thailand'),
('vitamins', 'online vitamin store thailand', 'online vitamin store thailand')
ON CONFLICT (search_term, category, keyword_en) DO NOTHING;
