version: 2

sources:
  - name: dtc
    database: postgres
    schema: dtc
    tables:
      - name: dtc_raw_google_search_results
        description: "Raw Google search results from Apify scraper."
        columns:
          - name: id
            description: "Primary key for the raw search results."
            data_tests:
              - unique
              - not_null
          - name: keyword_id
            description: "Foreign key to the dtc_keywords table."
            data_tests:
              - not_null
          - name: data
            description: "JSONB blob containing the search results."
            data_tests:
              - not_null
      - name: dtc_raw_instagram_profiles
        description: "Raw Instagram profile details from Apify scraper."
        columns:
          - name: id
            description: "Primary key for the raw Instagram profiles."
            data_tests:
              - unique
              - not_null
          - name: profile_id
            description: "Profile ID that matches dtc_profiles.id."
            data_tests:
              - not_null
          - name: data
            description: "JSONB blob containing the Instagram profile details."
            data_tests:
              - not_null

models:
  - name: stg_google_search_results
    description: "Staging model for raw Google search results. Renames columns for clarity."
    columns:
      - name: google_search_result_id
        description: "Primary key for the raw search results."
        data_tests:
          - unique
          - not_null
      - name: keyword_id
        description: "Foreign key to the dtc_keywords table."
        data_tests:
          - not_null

  - name: stg_google_search_organic_results
    description: "Staging model that unnests organic results from Google search results."
    columns:
      - name: url
        description: "URL from the organic search result."
        data_tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "LIKE '%instagram.com%'"

  - name: stg_instagram_profiles
    description: "Staging model for raw Instagram profiles data. Renames columns for clarity."
    columns:
      - name: dtc_raw_instagram_profile_id
        description: "Primary key for the raw Instagram profiles (from dtc_raw_instagram_profiles.id)."
        data_tests:
          - unique
          - not_null
      - name: profile_id
        description: "Profile ID that matches dtc_profiles.id."
        data_tests:
          - not_null 