version: 2

models:
  - name: profiles
    description: "Dimension table for Instagram profiles. Contains unique profiles identified during scrapes."
    columns:
      - name: id
        description: "Surrogate key for the profile."
        data_tests:
          - unique
          - not_null
      - name: username
        description: "Instagram username."
        data_tests:
          - not_null
      - name: profile_url
        description: "Full URL to the Instagram profile."

  - name: google_search_instagram_profiles
    description: "Intermediate model that extracts Instagram usernames from Google search results."
    columns:
      - name: username
        description: "Extracted Instagram username."
        data_tests:
          - not_null
      - name: search_term_id
        description: "Foreign key to the search_terms snapshot table."
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - search_term_id

  - name: profile_details
    description: "Historical fact table containing detailed Instagram profile information from every scrape."
    columns:
      - name: id
        description: "Surrogate key for the profile details record."
        data_tests:
          - unique
          - not_null
      - name: profile_id
        description: "Profile ID that matches dtc_profiles.id."
        data_tests:
          - not_null
      - name: instagram_id
        description: "Instagram's internal ID for the profile."
      - name: url
        description: "Instagram profile URL."
      - name: fbid
        description: "Facebook ID associated with the profile."
      - name: is_private
        description: "Whether the profile is private."
      - name: full_name
        description: "Full name of the profile."
      - name: input_url
        description: "Original input URL used for scraping."
      - name: username
        description: "Instagram username."
      - name: is_verified
        description: "Whether the profile is verified."
      - name: biography
        description: "Profile biography text."
      - name: has_channel
        description: "Whether the profile has a channel."
      - name: posts_count
        description: "Number of posts on the profile."
      - name: external_url
        description: "External URL from the profile."
      - name: follows_count
        description: "Number of accounts the profile follows."
      - name: profile_pic_url
        description: "URL of the profile picture."
      - name: followers_count
        description: "Number of followers."
      - name: igtv_video_count
        description: "Number of IGTV videos."
      - name: joined_recently
        description: "Whether the account joined recently."
      - name: profile_pic_url_hd
        description: "High definition profile picture URL."
      - name: is_business_account
        description: "Whether this is a business account."
      - name: external_url_shimmed
        description: "Shimmed external URL."
      - name: highlight_reel_count
        description: "Number of highlight reels."
      - name: business_category_name
        description: "Business category name if applicable."
      - name: created_at
        description: "Timestamp when this record was created."
        data_tests:
          - not_null

  - name: profile_search_terms
    description: "Associates profiles with the search terms used to find them."
    columns:
      - name: profile_id
        description: "Foreign key to the profiles table."
        data_tests:
          - not_null
      - name: search_term_id
        description: "Foreign key to the snapshot_search_terms table."
        data_tests:
          - not_null

  - name: profiles_with_latest_details
    description: "Final, user-facing model showing the most recently scraped details for each profile."
    columns:
      - name: profile_id
        description: "Surrogate key from the profiles table."
        data_tests:
          - unique
          - not_null
      - name: username
        description: "Instagram username."
      - name: full_name
        description: "Most recent full name."
      - name: biography
        description: "Most recent biography."
      - name: followers_count
        description: "Most recent follower count."
      - name: posts_count
        description: "Most recent post count."
      - name: last_scraped_at
        description: "Timestamp of the last scrape for this profile."

 